server:
  port: 8081

openai:
  api:
    key: ${OPENAI_API_KEY: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}

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/storemanager
    username: ${DB_USERNAME:admin}
    password: ${DB_PASSWORD:secret}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

management:
  endpoints:
    web:
      exposure:
        include: "*"
