server:
  port: 8081

openai:
  api:
    key: ${OPENAI_API_KEY}

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/storemanager
    username: ${DB_USERNAME:admin}
    password: ${DB_PASSWORD:secret}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

management:
  endpoints:
    web:
      exposure:
        include: "*"
